### ISSUE TITLE
Allow nice alternative name to be passed via GET args

### ISSUE THREAD

**Issue by dmlb2000** [EMSL-MSC/pacifica-cartd#29]
We should set the http header `Content-Disposition` as defined [here](https://www.w3.org/Protocols/rfc2616/rfc2616-sec19.html#sec19.5.1) so that the browser will save the file as an alternative nice name. We should pass this to the service as a GET argument.

`curl -v localhost:8081/cartid-skdrcncvlaskenskerjf?filename=my-custom-cart-name.tar` then if you inspect the headers `Content-Disposition: attachment; filename="my-custom-cart-name.tar"` should be in there.

This should allow redirects to this service from a browser to save the tarfile in a nice way on a users desktop.

**Comment by dmlb2000** [comment]
@kauberry will this work when you do your redirect from the status page?

**Comment by kauberry** [comment]
I can handle that. I was planning on adding that sort of capability to the cart download interface anyway, so you're a step ahead of me. =)
